/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AccountsAccountIdIndexImport } from './routes/accounts/$accountId/index'
import { Route as AccountsAccountIdPaymentIndexImport } from './routes/accounts/$accountId/payment/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AccountsAccountIdIndexRoute = AccountsAccountIdIndexImport.update({
  path: '/accounts/$accountId/',
  getParentRoute: () => rootRoute,
} as any)

const AccountsAccountIdPaymentIndexRoute =
  AccountsAccountIdPaymentIndexImport.update({
    path: '/accounts/$accountId/payment/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/accounts/$accountId/': {
      preLoaderRoute: typeof AccountsAccountIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/accounts/$accountId/payment/': {
      preLoaderRoute: typeof AccountsAccountIdPaymentIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutRoute,
  AccountsAccountIdIndexRoute,
  AccountsAccountIdPaymentIndexRoute,
])

/* prettier-ignore-end */
